openapi: 3.0.0
info:
  title: Statement-Path-Details
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /hn-statements-api/v1/api/statement-path-details:
    post:
      tags:
        - General
      summary: statement-path-details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                dsId: '100496617'
                orderStartDate: '2014-12-01'
                orderEndDate: '2016-12-01'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
